create table public.account (
                                id int8 generated by default as identity,
                                balance float8,
                                currency_code varchar(255),
                                created_at timestamp,
                                name varchar(255),
                                status varchar(255),
                                type varchar(255),
                                updated_at timestamp,
                                client_id int8,
                                primary key (id)
);

create table public.agreement (
                                  id int8 generated by default as identity,
                                  created_at timestamp,
                                  interest_rate float8,
                                  status varchar(255),
                                  sum float8,
                                  updated_at timestamp,
                                  account_id int8,
                                  product_id int8,
                                  primary key (id)
);

create table public.client (
                               id int8 generated by default as identity,
                               address varchar(255),
                               created_at timestamp,
                               email varchar(255),
                               first_name varchar(255),
                               last_name varchar(255),
                               phone varchar(255),
                               status varchar(255),
                               tax_code varchar(255),
                               updated_at timestamp,
                               manager_id int8,
                               primary key (id)
);

create table public.manager (
                                id int8 generated by default as identity,
                                created_at timestamp,
                                first_name varchar(255),
                                last_name varchar(255),
                                status varchar(255),
                                updated_at timestamp,
                                primary key (id)
);

create table public.product (
                                id int8 generated by default as identity,
                                created_at timestamp,
                                currency_code varchar(255),
                                interest_rate float8,
                                name varchar(255),
                                product_limit int4,
                                status varchar(255),
                                updated_at timestamp,
                                manager_id int8,
                                primary key (id)
);

create table transaction (
                             id int8 generated by default as identity,
                             amount float8,
                             created_at timestamp,
                             description varchar(255),
                             type varchar(255),
                             credit_account_id int8,
                             debit_account_id int8,
                             primary key (id)
);

alter table if exists public.account
    add constraint account_client_id_fkey
        foreign key (client_id)
            references public.client;

alter table if exists public.agreement
    add constraint agreement_account_id_fkey
        foreign key (account_id)
            references public.account;

alter table if exists public.agreement
    add constraint agreement_product_id_fkey
        foreign key (product_id)
            references public.product;

alter table if exists public.client
    add constraint client_manager_id_fkey
        foreign key (manager_id)
            references public.manager;

alter table if exists public.product
    add constraint product_manager_id_fkey
        foreign key (manager_id)
            references public.manager;

alter table if exists transaction
    add constraint transaction_credit_account_id_fkey
        foreign key (credit_account_id)
            references public.account;

alter table if exists transaction
    add constraint transaction_debit_account_id_fkey
        foreign key (debit_account_id)
            references public.account;