DROP TABLE IF EXISTS manager CASCADE ;
DROP TABLE IF EXISTS product CASCADE ;
DROP TABLE IF EXISTS client CASCADE ;
DROP TABLE IF EXISTS agreement CASCADE ;
DROP TABLE IF EXISTS account CASCADE ;
DROP TABLE IF EXISTS transaction CASCADE ;
